baseURL = "https://binjuhor.com/"
languageCode = "en-us"
title = "Kiem Hoang's portfolio"
theme = "uilite"

[[menu.primaryMenu]]
    name = "Kiem Hoang" 
    weight = 10 
    url = "/"

[[menu.secondaryMenu]]
    name = "Blogs"
    weight = 20
    url = "/blog/"

[[menu.secondaryMenu]]
    name = "Work"
    weight = 30
    url = "/work/"

[[menu.secondaryMenu]]
    name = "Contact"
    weight = 40
    url = "/#contact"
