baseURL = "https://binjuhor.com/"
languageCode = "en-us"
title = "Kiem Hoang Personal Portfolio"
theme = "uilite"
recaptchaKey = "6Lf-VeAcAAAAAJm9iw3J8SigdmQqz2TLtH340wkt"
   
[[menu.primary]]
    name = "Kiem Hoang" 
    weight = 10 
    url = "/"

[[menu.secondary]]
    name = "Work"
    weight = 30
    url = "/work/"

[[menu.secondary]]
    name = "Contact"
    weight = 40
    url = "/#contact"
